// 样式配置
const STYLES = {
  'default': {
    name: '公众号风格',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0px 40px 0px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 15px; line-height: 1.75 !important; color: #3f3f3f !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #2c3e50 !important; line-height: 1.3 !important; margin: 40px 0 20px; padding-bottom: 8px; border-bottom: 2px solid #3498db;',
      h2: 'font-size: 24px; font-weight: 700; color: #2c3e50 !important; line-height: 1.35 !important; margin: 32px 0 16px; padding-left: 12px; border-left: 4px solid #3498db;',
      h3: 'font-size: 20px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #34495e !important; line-height: 1.45 !important; margin: 24px 0 12px;',
      h5: 'font-size: 16px; font-weight: 600; color: #34495e !important; line-height: 1.5 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 600; color: #34495e !important; line-height: 1.5 !important; margin: 16px 0 8px;',
      p: 'font-size: 15px; margin: 20px 0 !important; line-height: 1.75 !important; color: #3f3f3f !important;',
      strong: 'font-weight: 700; color: #2c3e50 !important;',
      em: 'font-style: italic; color: #555 !important;',
      a: 'color: #3498db !important; text-decoration: none; border-bottom: 1px solid #3498db;',
      ul: 'margin: 20px 0; padding-left: 24px;',
      ol: 'margin: 20px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.75 !important;',
      blockquote: 'font-size: 15px; margin: 24px 0; padding: 10px 16px; background-color: #fafafa !important; border-left: 3px solid #999; color: #666 !important; line-height: 1.75 !important;',
      code: 'font-family: Consolas, Monaco, "Courier New", monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #e74c3c !important; border-radius: 3px;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #2d2d2d !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 40px 0; border: none; border-top: 1px solid #e0e0e0;',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 24px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'font-size: 14px; line-height: 1.6 !important; background-color: #f0f0f0 !important; padding: 10px 12px; text-align: left; border: 1px solid #e0e0e0; font-weight: 600;',
      td: 'font-size: 15px; line-height: 1.6 !important; padding: 10px 12px; text-align: left; border: 1px solid #e0e0e0;',
      tr: 'border-bottom: 1px solid #e0e0e0;',
    }
  },

  'latepost-depth': {
    name: '晚点风格',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0px 40px 0px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #1a1a1a !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #1a1a1a !important; line-height: 1.3 !important; margin: 40px 0 20px; padding-left: 20px; border-left: 6px solid #d32f2f; position: relative;',
      h2: 'font-size: 24px; font-weight: 700; color: #fff !important; line-height: 1.35 !important; margin: 32px 0 16px; padding: 16px 24px; background-color: #d32f2f !important; border-radius: 4px; position: relative;',
      h3: 'font-size: 20px; font-weight: 600; color: #d32f2f !important; line-height: 1.4 !important; margin: 28px 0 14px; padding-left: 16px; border-left: 4px solid #d32f2f; position: relative;',
      h4: 'font-size: 18px; font-weight: 600; color: #1a1a1a !important; line-height: 1.45 !important; margin: 24px 0 12px; padding: 8px 12px; background-color: #f5f5f5 !important; border-left: 3px solid #ff5252;',
      h5: 'font-size: 16px; font-weight: 600; color: #333 !important; line-height: 1.5 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 600; color: #666 !important; line-height: 1.5 !important; margin: 16px 0 8px;',
      p: 'font-size: 15px; margin: 20px 0 !important; line-height: 1.75 !important; color: #1a1a1a !important;',
      strong: 'font-weight: 700; color: #d32f2f !important; background-color: rgba(211, 47, 47, 0.08) !important; padding: 2px 6px; border-radius: 3px;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #d32f2f !important; text-decoration: none; border-bottom: 1px solid #d32f2f;',
      ul: 'margin: 20px 0; padding-left: 24px; list-style-type: disc;',
      ol: 'margin: 20px 0; padding-left: 24px; list-style-type: decimal;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.75 !important; color: #1a1a1a !important;',
      blockquote: 'font-size: 15px; margin: 24px 0; padding: 16px 20px 16px 18px; background-color: #f5f5f5 !important; border-left: 4px solid #d32f2f; color: #1a1a1a !important; line-height: 1.75 !important; position: relative; border-radius: 4px;',
      code: 'font-family: "SF Mono", Menlo, Consolas, monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #d32f2f !important; border-radius: 4px; font-weight: 500;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #2a2a2a !important; color: #f5f5f5 !important; border-radius: 6px; overflow-x: auto; line-height: 1.6 !important; border-left: 4px solid #d32f2f;',
      hr: 'margin: 40px 0; border: none; height: 2px; background: linear-gradient(to right, transparent, #d32f2f, transparent); max-width: 200px;',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 24px auto; border-radius: 6px; box-shadow: 0 4px 12px rgba(211, 47, 47, 0.12);',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px; border-radius: 6px; overflow: hidden;',
      th: 'font-size: 14px; line-height: 1.6 !important; background-color: #d32f2f !important; color: #fff !important; padding: 10px 12px; text-align: left; font-weight: 600; border: none;',
      td: 'font-size: 15px; line-height: 1.6 !important; padding: 10px 12px; text-align: left; border: none; border-bottom: 1px solid #e0e0e0; color: #1a1a1a !important; background-color: #fff !important;',
      tr: 'border-bottom: 1px solid #e0e0e0;',
    }
  },

  'tech': {
    name: '技术风格',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0px 40px 0px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 15px; line-height: 1.75 !important; color: #2c3e50 !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #1a1a1a !important; line-height: 1.3 !important; margin: 40px 0 20px; padding: 0 0 12px; border-bottom: 3px solid #0066cc;',
      h2: 'font-size: 24px; font-weight: 700; color: #1a1a1a !important; line-height: 1.35 !important; margin: 32px 0 16px; padding-left: 16px; padding-top: 4px; padding-bottom: 4px; border-left: 5px solid #00a67d; background: linear-gradient(to right, #f0f9ff 0%, transparent 100%);',
      h3: 'font-size: 20px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 28px 0 14px; padding-left: 12px; border-left: 3px solid #ff9800;',
      h4: 'font-size: 18px; font-weight: 600; color: #34495e !important; line-height: 1.45 !important; margin: 24px 0 12px;',
      h5: 'font-size: 16px; font-weight: 600; color: #34495e !important; line-height: 1.5 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 600; color: #34495e !important; line-height: 1.5 !important; margin: 16px 0 8px;',
      p: 'font-size: 15px; margin: 20px 0 !important; line-height: 1.75 !important; color: #3a3a3a !important;',
      strong: 'font-weight: 700; color: #1a1a1a !important; background-color: #fff3cd !important; padding: 2px 4px; border-radius: 8px;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #0066cc !important; text-decoration: none; border-bottom: 1px solid #0066cc;',
      ul: 'margin: 20px 0; padding-left: 24px;',
      ol: 'margin: 20px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.75 !important; color: #3a3a3a !important;',
      blockquote: 'font-size: 15px; margin: 24px 0; padding: 10px 16px; background-color: #f5f9fc !important; border-left: 3px solid #2196f3; color: #555 !important; line-height: 1.75 !important;',
      code: 'font-family: "Fira Code", Consolas, Monaco, "Courier New", monospace; font-size: 14px; padding: 2px 6px; background-color: #ffe6e6 !important; color: #d63031 !important; border-radius: 8px; font-weight: 500;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #1e1e1e !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important; box-shadow: 0 2px 8px rgba(0,0,0,0.1);',
      hr: 'margin: 40px 0; border: none; height: 2px; background: linear-gradient(to right, transparent, #0066cc, transparent);',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 24px auto; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px; box-shadow: 0 1px 4px rgba(0,0,0,0.1);',
      th: 'font-size: 14px; line-height: 1.6 !important; background-color: #0066cc !important; color: #fff !important; padding: 10px 12px; text-align: left; border: 1px solid #0052a3; font-weight: 600;',
      td: 'font-size: 15px; line-height: 1.6 !important; padding: 10px 12px; text-align: left; border: 1px solid #e0e0e0; background-color: #fff !important;',
      tr: 'border-bottom: 1px solid #e0e0e0;',
    }
  },

  'deepread': {
    name: '深度阅读',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0px 40px 0px; font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 15px; line-height: 1.75 !important; color: #1a1a1a !important; word-wrap: break-word; letter-spacing: 0.01em;',
      h1: 'font-size: 28px; font-weight: 700; color: #0a0a0a !important; line-height: 1.3 !important; margin: 40px 0 20px; letter-spacing: -0.02em;',
      h2: 'font-size: 24px; font-weight: 700; color: #0a0a0a !important; line-height: 1.35 !important; margin: 32px 0 16px; letter-spacing: -0.01em;',
      h3: 'font-size: 20px; font-weight: 600; color: #1a1a1a !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #2a2a2a !important; line-height: 1.45 !important; margin: 24px 0 12px;',
      h5: 'font-size: 16px; font-weight: 600; color: #3a3a3a !important; line-height: 1.5 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 600; color: #4a4a4a !important; line-height: 1.5 !important; margin: 16px 0 8px;',
      p: 'font-size: 15px; margin: 20px 0 !important; line-height: 1.75 !important; color: #1a1a1a !important;',
      strong: 'font-weight: 700; color: #0a0a0a !important;',
      em: 'font-style: italic; color: #2a2a2a !important;',
      a: 'color: #0066cc !important; text-decoration: none; border-bottom: 1px solid #0066cc;',
      ul: 'margin: 20px 0; padding-left: 24px;',
      ol: 'margin: 20px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.75 !important; color: #1a1a1a !important;',
      blockquote: 'font-size: 15px; margin: 24px 0; padding: 16px 20px; background-color: #f8f9fa !important; border-left: 4px solid #0a0a0a; color: #1a1a1a !important; line-height: 1.75 !important; font-style: normal;',
      code: 'font-family: "SF Mono", Consolas, Monaco, "Courier New", monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #d73a49 !important; border-radius: 3px;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f6f8fa !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important; border: 1px solid #e1e4e8;',
      hr: 'margin: 40px 0; border: none; height: 1px; background-color: #e1e4e8 !important;',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 24px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'font-size: 14px; line-height: 1.6 !important; background-color: #f6f8fa !important; padding: 10px 12px; text-align: left; border: 1px solid #e1e4e8; font-weight: 600; color: #1a1a1a !important;',
      td: 'font-size: 15px; line-height: 1.6 !important; padding: 10px 12px; text-align: left; border: 1px solid #e1e4e8; color: #1a1a1a !important;',
      tr: 'border-bottom: 1px solid #e1e4e8;',
    }
  },

'new-york': {
    name: '纽约时报',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0px 40px 0px; font-family: Georgia, "Times New Roman", Times, serif; font-size: 15px; line-height: 1.75 !important; color: #121212 !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #000 !important; line-height: 1.3 !important; margin: 40px 0 20px; font-family: Georgia, serif; letter-spacing: -0.02em; border-bottom: 1px solid #000; padding-bottom: 16px;',
      h2: 'font-size: 24px; font-weight: 700; color: #000 !important; line-height: 1.35 !important; margin: 32px 0 16px; font-family: Georgia, serif; letter-spacing: -0.01em;',
      h3: 'font-size: 20px; font-weight: 600; color: #121212 !important; line-height: 1.4 !important; margin: 28px 0 14px; font-family: Georgia, serif;',
      h4: 'font-size: 18px; font-weight: 600; color: #1a1a1a !important; line-height: 1.45 !important; margin: 24px 0 12px; font-family: Georgia, serif;',
      h5: 'font-size: 16px; font-weight: 600; color: #2a2a2a !important; line-height: 1.5 !important; margin: 20px 0 10px; font-family: Georgia, serif;',
      h6: 'font-size: 15px; font-weight: 600; color: #3a3a3a !important; line-height: 1.5 !important; margin: 16px 0 8px; font-family: Georgia, serif; font-style: italic;',
      p: 'font-size: 15px; margin: 20px 0 !important; line-height: 1.75 !important; color: #121212 !important; text-align: left;',
      strong: 'font-weight: 700; color: #000 !important;',
      em: 'font-style: italic; color: #121212 !important;',
      a: 'color: #326891 !important; text-decoration: none; border-bottom: 1px solid #326891; word-break: break-all;',
      ul: 'margin: 20px 0; padding-left: 26px;',
      ol: 'margin: 20px 0; padding-left: 26px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.75 !important; color: #121212 !important; text-align: left;',
      blockquote: 'font-size: 15px; margin: 24px 0; padding: 16px 24px; background-color: #f7f7f7 !important; border-left: 5px solid #121212; color: #121212 !important; line-height: 1.75 !important; font-style: italic; font-family: Georgia, serif;',
      code: 'font-family: "Courier New", Courier, monospace; font-size: 14px; padding: 2px 6px; background-color: #f0f0f0 !important; color: #666 !important; border: 1px solid #ddd;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f7f7f7 !important; border: 1px solid #ddd; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 40px 0; border: none; height: 1px; background-color: #ddd !important; max-width: 100px;',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 24px auto;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px; border: 1px solid #ddd;',
      th: 'font-size: 14px; line-height: 1.6 !important; background-color: #f7f7f7 !important; padding: 10px 12px; text-align: left; border: 1px solid #ddd; font-weight: 700; color: #121212 !important; font-family: Georgia, serif;',
      td: 'font-size: 15px; line-height: 1.6 !important; padding: 10px 12px; text-align: left; border: 1px solid #ddd; color: #121212 !important;',
      tr: 'border-bottom: 1px solid #ddd;',
    }
  },

  'anthropic': {
    name: 'Claude',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0px 40px 0px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif; font-size: 15px; line-height: 1.75 !important; color: #2b2b2b !important; word-wrap: break-word; letter-spacing: -0.01em;',
      h1: 'font-size: 28px; font-weight: 700; color: #191919 !important; line-height: 1.3 !important; margin: 40px 0 20px; letter-spacing: -0.025em; background: linear-gradient(135deg, #C15F3C 0%, #e97d5b 50%, #CC8B7A 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent !important;',
      h2: 'font-size: 24px; font-weight: 700; color: #191919 !important; line-height: 1.35 !important; margin: 32px 0 16px; letter-spacing: -0.02em; background: linear-gradient(135deg, #C15F3C 0%, #9DC88D 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent !important;',
      h3: 'font-size: 20px; font-weight: 600; color: #2b2b2b !important; line-height: 1.4 !important; margin: 28px 0 14px; letter-spacing: -0.015em;',
      h4: 'font-size: 18px; font-weight: 600; color: #3a3a3a !important; line-height: 1.45 !important; margin: 24px 0 12px; letter-spacing: -0.01em;',
      h5: 'font-size: 16px; font-weight: 600; color: #4a4a4a !important; line-height: 1.5 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 600; color: #5a5a5a !important; line-height: 1.5 !important; margin: 16px 0 8px;',
      p: 'font-size: 15px; margin: 20px 0 !important; line-height: 1.75 !important; color: #2b2b2b !important; letter-spacing: -0.005em;',
      strong: 'font-weight: 700; color: #C15F3C !important; background-color: rgba(193, 95, 60, 0.08) !important; padding: 2px 6px; border-radius: 3px;',
      em: 'font-style: italic; color: #5a5a5a !important;',
      a: 'color: #C15F3C !important; text-decoration: none; border-bottom: 1px solid rgba(193, 95, 60, 0.4); font-weight: 500;',
      ul: 'margin: 20px 0; padding-left: 24px;',
      ol: 'margin: 20px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.75 !important; color: #2b2b2b !important;',
      blockquote: 'font-size: 15px; margin: 24px 0; padding: 18px 22px; background: linear-gradient(135deg, rgba(193, 95, 60, 0.06) 0%, rgba(157, 200, 141, 0.06) 100%); border-left: 4px solid #C15F3C; color: #2b2b2b !important; line-height: 1.75 !important; font-style: italic; border-radius: 8px;',
      code: 'font-family: "SF Mono", Consolas, Monaco, monospace; font-size: 14px; padding: 2px 6px; background-color: rgba(193, 95, 60, 0.08) !important; color: #C15F3C !important; border-radius: 8px; font-weight: 500; border: 1px solid rgba(193, 95, 60, 0.15);',
      pre: 'margin: 24px 0; padding: 20px; background: linear-gradient(135deg, #2b2b2b 0%, #3a3a3a 100%); color: #f5f5f5 !important; border-radius: 12px; overflow-x: auto; line-height: 1.6 !important; box-shadow: 0 4px 20px rgba(193, 95, 60, 0.15);',
      hr: 'margin: 40px 0; border: none; height: 2px; background: linear-gradient(to right, transparent, rgba(193, 95, 60, 0.3), rgba(157, 200, 141, 0.3), transparent); max-width: 240px;',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 24px auto; border-radius: 12px; box-shadow: 0 8px 32px rgba(193, 95, 60, 0.12);',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px; border-radius: 8px; overflow: hidden;',
      th: 'font-size: 14px; line-height: 1.6 !important; background: linear-gradient(135deg, rgba(193, 95, 60, 0.08) 0%, rgba(157, 200, 141, 0.08) 100%); padding: 10px 12px; text-align: left; border: none; font-weight: 600; color: #2b2b2b !important; border-bottom: 2px solid rgba(193, 95, 60, 0.2);',
      td: 'font-size: 15px; line-height: 1.6 !important; padding: 10px 12px; text-align: left; border: none; border-bottom: 1px solid rgba(193, 95, 60, 0.1); color: #2b2b2b !important;',
      tr: 'border: none;',
    }
  },

  'nikkei': {
    name: 'Nikkei 日経',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0px 40px 0px; font-family: "Hiragino Kaku Gothic ProN", "Yu Gothic", "Meiryo", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #1a1a1a !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #000 !important; line-height: 1.3 !important; margin: 40px 0 20px; padding-bottom: 8px; border-bottom: 2px solid #000;',
      h2: 'font-size: 24px; font-weight: 700; color: #c41230 !important; line-height: 1.35 !important; margin: 32px 0 16px; padding-left: 10px; border-left: 3px solid #c41230;',
      h3: 'font-size: 20px; font-weight: 600; color: #000 !important; line-height: 1.4 !important; margin: 28px 0 14px; padding: 4px 8px; background-color: #f5f5f5 !important;',
      h4: 'font-size: 18px; font-weight: 600; color: #333 !important; line-height: 1.45 !important; margin: 24px 0 12px; text-decoration: underline; text-decoration-color: #c41230; text-underline-offset: 3px;',
      h5: 'font-size: 16px; font-weight: 600; color: #666 !important; line-height: 1.5 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 600; color: #999 !important; line-height: 1.5 !important; margin: 16px 0 8px;',
      p: 'font-size: 15px; margin: 20px 0 !important; line-height: 1.75 !important; color: #1a1a1a !important; text-align: justify;',
      strong: 'font-weight: 700; color: #000 !important; background-color: #fff3f3 !important; padding: 0 2px;',
      em: 'font-style: italic; color: #c41230 !important; font-weight: 600;',
      a: 'color: #0066cc !important; text-decoration: none; border-bottom: 1px solid #0066cc;',
      ul: 'margin: 20px 0; padding-left: 24px; list-style-type: disc;',
      ol: 'margin: 20px 0; padding-left: 24px; list-style-type: decimal;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.75 !important; color: #1a1a1a !important;',
      blockquote: 'font-size: 15px; margin: 24px 0; padding: 12px 15px; background-color: transparent !important; border-left: 2px solid #c41230; border-right: 2px solid #c41230; color: #1a1a1a !important; line-height: 1.75 !important;',
      code: 'font-family: "Courier New", monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #c41230 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f5f5f5 !important; border: 1px solid #ddd; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 40px 0; border: none; height: 1px; background-color: #000 !important;',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 24px auto;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px; border: 1px solid #000;',
      th: 'font-size: 14px; line-height: 1.6 !important; background-color: #c41230 !important; color: #fff !important; padding: 10px 12px; text-align: left; font-weight: 600; border: 1px solid #c41230;',
      td: 'font-size: 15px; line-height: 1.6 !important; padding: 10px 12px; text-align: left; border: 1px solid #ddd; color: #1a1a1a !important; background-color: #fff !important;',
      tr: 'border-bottom: 1px solid #ddd;',
    }
  },

  'atlantic-feature': {
    name: 'Atlantic 特稿',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0px 40px 0px; font-family: Georgia, "Times New Roman", serif; font-size: 15px; line-height: 1.75 !important; color: #1c1c1c !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 40px 0 20px; letter-spacing: -0.02em; border-bottom: 2px solid #c44b34; padding-bottom: 10px;',
      h2: 'font-size: 24px; font-weight: 700; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px; padding-left: 12px; border-left: 4px solid #c44b34;',
      h3: 'font-size: 20px; font-weight: 600; color: #222 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #333 !important; line-height: 1.45 !important; margin: 24px 0 12px;',
      h5: 'font-size: 16px; font-weight: 600; color: #444 !important; line-height: 1.5 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 600; color: #555 !important; line-height: 1.5 !important; margin: 16px 0 8px;',
      p: 'font-size: 15px; margin: 20px 0 !important; line-height: 1.75 !important; color: #1c1c1c !important;',
      strong: 'font-weight: 700; color: #111 !important; background-color: rgba(196, 75, 52, 0.08) !important; padding: 1px 4px;',
      em: 'font-style: italic; color: #5a5a5a !important;',
      a: 'color: #c44b34 !important; text-decoration: none; border-bottom: 1px solid #c44b34;',
      ul: 'margin: 20px 0; padding-left: 24px;',
      ol: 'margin: 20px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.75 !important; color: #1c1c1c !important;',
      blockquote: 'font-size: 15px; margin: 24px 0; padding: 16px 20px; background-color: #faf7f4 !important; border-left: 4px solid #c44b34; color: #333 !important; line-height: 1.75 !important; font-style: italic;',
      code: 'font-family: "SF Mono", Menlo, Consolas, monospace; font-size: 14px; padding: 2px 6px; background-color: #f4efea !important; color: #9b2c1d !important; border-radius: 3px;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #23201e !important; color: #f7f2ec !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 40px 0; border: none; height: 1px; background-color: #d7ccc3 !important;',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 24px auto; border-radius: 6px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'font-size: 14px; line-height: 1.6 !important; background-color: #f6f1eb !important; padding: 10px 12px; text-align: left; border: 1px solid #e4d8cd; font-weight: 700; color: #1c1c1c !important;',
      td: 'font-size: 15px; line-height: 1.6 !important; padding: 10px 12px; text-align: left; border: 1px solid #e4d8cd; color: #1c1c1c !important;',
      tr: 'border-bottom: 1px solid #e4d8cd;',
    }
  },

  'monocle-brief': {
    name: 'Monocle 简报',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0px 40px 0px; font-family: -apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif; font-size: 15px; line-height: 1.75 !important; color: #202020 !important; word-wrap: break-word; letter-spacing: 0.01em;',
      h1: 'font-size: 28px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 40px 0 20px; text-transform: uppercase; letter-spacing: 0.04em; border-bottom: 2px solid #111; padding-bottom: 8px;',
      h2: 'font-size: 24px; font-weight: 700; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px; text-transform: uppercase; letter-spacing: 0.03em;',
      h3: 'font-size: 20px; font-weight: 600; color: #222 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #333 !important; line-height: 1.45 !important; margin: 24px 0 12px;',
      h5: 'font-size: 16px; font-weight: 600; color: #444 !important; line-height: 1.5 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 600; color: #666 !important; line-height: 1.5 !important; margin: 16px 0 8px;',
      p: 'font-size: 15px; margin: 20px 0 !important; line-height: 1.75 !important; color: #202020 !important;',
      strong: 'font-weight: 700; color: #111 !important; background-color: #f0e9dc !important; padding: 1px 4px;',
      em: 'font-style: italic; color: #555 !important;',
      a: 'color: #111 !important; text-decoration: none; border-bottom: 1px solid #b08a42;',
      ul: 'margin: 20px 0; padding-left: 24px;',
      ol: 'margin: 20px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.75 !important; color: #202020 !important;',
      blockquote: 'font-size: 15px; margin: 24px 0; padding: 14px 18px; background-color: #f8f6f1 !important; border-left: 3px solid #b08a42; color: #333 !important; line-height: 1.75 !important;',
      code: 'font-family: "SF Mono", Menlo, Consolas, monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f1e8 !important; color: #8c5f12 !important; border-radius: 3px;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #1f1f1f !important; color: #f5f5f5 !important; border-radius: 6px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 40px 0; border: none; height: 2px; background-color: #111 !important;',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'font-size: 14px; line-height: 1.6 !important; background-color: #f3efe7 !important; padding: 10px 12px; text-align: left; border-bottom: 2px solid #111; font-weight: 700; color: #111 !important;',
      td: 'font-size: 15px; line-height: 1.6 !important; padding: 10px 12px; text-align: left; border-bottom: 1px solid #e4ddd0; color: #202020 !important;',
      tr: 'border-bottom: 1px solid #e4ddd0;',
    }
  },

  'sspai-column': {
    name: '少数派专栏',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0px 40px 0px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Segoe UI", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #1f2328 !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #111827 !important; line-height: 1.3 !important; margin: 40px 0 20px; border-bottom: 2px solid #4f8cff; padding-bottom: 10px;',
      h2: 'font-size: 24px; font-weight: 700; color: #111827 !important; line-height: 1.35 !important; margin: 32px 0 16px; padding-left: 12px; border-left: 4px solid #4f8cff;',
      h3: 'font-size: 20px; font-weight: 600; color: #1f2937 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #374151 !important; line-height: 1.45 !important; margin: 24px 0 12px;',
      h5: 'font-size: 16px; font-weight: 600; color: #4b5563 !important; line-height: 1.5 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 600; color: #6b7280 !important; line-height: 1.5 !important; margin: 16px 0 8px;',
      p: 'font-size: 15px; margin: 20px 0 !important; line-height: 1.75 !important; color: #1f2328 !important;',
      strong: 'font-weight: 700; color: #111827 !important; background-color: rgba(79, 140, 255, 0.10) !important; padding: 1px 4px; border-radius: 4px;',
      em: 'font-style: italic; color: #4b5563 !important;',
      a: 'color: #2563eb !important; text-decoration: none; border-bottom: 1px solid #93c5fd;',
      ul: 'margin: 20px 0; padding-left: 24px;',
      ol: 'margin: 20px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.75 !important; color: #1f2328 !important;',
      blockquote: 'font-size: 15px; margin: 24px 0; padding: 16px 20px; background-color: #f5f9ff !important; border-left: 4px solid #4f8cff; color: #374151 !important; line-height: 1.75 !important; border-radius: 6px;',
      code: 'font-family: "SF Mono", Menlo, Consolas, monospace; font-size: 14px; padding: 2px 6px; background-color: #eef4ff !important; color: #1d4ed8 !important; border-radius: 4px;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #1f2937 !important; color: #f9fafb !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 40px 0; border: none; height: 1px; background-color: #dbe4f0 !important;',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 24px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'font-size: 14px; line-height: 1.6 !important; background-color: #eef4ff !important; padding: 10px 12px; text-align: left; border: 1px solid #dbe4f0; font-weight: 600; color: #1f2937 !important;',
      td: 'font-size: 15px; line-height: 1.6 !important; padding: 10px 12px; text-align: left; border: 1px solid #dbe4f0; color: #1f2328 !important;',
      tr: 'border-bottom: 1px solid #dbe4f0;',
    }
  },

  'renwu-profile': {
    name: '人物特稿',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0px 40px 0px; font-family: Georgia, "PingFang SC", "Hiragino Sans GB", serif; font-size: 15px; line-height: 1.75 !important; color: #1b1b1b !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 40px 0 20px; letter-spacing: -0.02em; border-bottom: 1px solid #c9b8a6; padding-bottom: 12px;',
      h2: 'font-size: 24px; font-weight: 700; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px; padding-left: 12px; border-left: 4px solid #8c6a4a;',
      h3: 'font-size: 20px; font-weight: 600; color: #222 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #333 !important; line-height: 1.45 !important; margin: 24px 0 12px;',
      h5: 'font-size: 16px; font-weight: 600; color: #444 !important; line-height: 1.5 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 600; color: #666 !important; line-height: 1.5 !important; margin: 16px 0 8px;',
      p: 'font-size: 15px; margin: 20px 0 !important; line-height: 1.75 !important; color: #1b1b1b !important;',
      strong: 'font-weight: 700; color: #111 !important; background-color: rgba(140, 106, 74, 0.10) !important; padding: 1px 4px;',
      em: 'font-style: italic; color: #6b5a4f !important;',
      a: 'color: #8c6a4a !important; text-decoration: none; border-bottom: 1px solid #c9b8a6;',
      ul: 'margin: 20px 0; padding-left: 24px;',
      ol: 'margin: 20px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.75 !important; color: #1b1b1b !important;',
      blockquote: 'font-size: 15px; margin: 24px 0; padding: 16px 20px; background-color: #faf6f1 !important; border-left: 4px solid #8c6a4a; color: #3d342d !important; line-height: 1.75 !important; font-style: italic;',
      code: 'font-family: "SF Mono", Menlo, Consolas, monospace; font-size: 14px; padding: 2px 6px; background-color: #f6efe7 !important; color: #8c3d2a !important; border-radius: 4px;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #2b2521 !important; color: #f7f2eb !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 40px 0; border: none; height: 1px; background-color: #d8cabc !important;',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 24px auto; border-radius: 6px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'font-size: 14px; line-height: 1.6 !important; background-color: #f8f3ed !important; padding: 10px 12px; text-align: left; border: 1px solid #e5d8cb; font-weight: 600; color: #1b1b1b !important;',
      td: 'font-size: 15px; line-height: 1.6 !important; padding: 10px 12px; text-align: left; border: 1px solid #e5d8cb; color: #1b1b1b !important;',
      tr: 'border-bottom: 1px solid #e5d8cb;',
    }
  },

  'biz-insight': {
    name: '商业观察',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0px 40px 0px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Segoe UI", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #17202a !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #0f1720 !important; line-height: 1.3 !important; margin: 40px 0 20px; border-bottom: 2px solid #0f766e; padding-bottom: 10px;',
      h2: 'font-size: 24px; font-weight: 700; color: #0f1720 !important; line-height: 1.35 !important; margin: 32px 0 16px; padding-left: 12px; border-left: 4px solid #0f766e;',
      h3: 'font-size: 20px; font-weight: 600; color: #14323f !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #274454 !important; line-height: 1.45 !important; margin: 24px 0 12px;',
      h5: 'font-size: 16px; font-weight: 600; color: #39586b !important; line-height: 1.5 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 600; color: #4f6b7a !important; line-height: 1.5 !important; margin: 16px 0 8px;',
      p: 'font-size: 15px; margin: 20px 0 !important; line-height: 1.75 !important; color: #17202a !important;',
      strong: 'font-weight: 700; color: #0f1720 !important; background-color: rgba(15, 118, 110, 0.10) !important; padding: 1px 4px; border-radius: 4px;',
      em: 'font-style: italic; color: #46606f !important;',
      a: 'color: #0f766e !important; text-decoration: none; border-bottom: 1px solid #5eead4;',
      ul: 'margin: 20px 0; padding-left: 24px;',
      ol: 'margin: 20px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.75 !important; color: #17202a !important;',
      blockquote: 'font-size: 15px; margin: 24px 0; padding: 16px 20px; background-color: #f0fdfa !important; border-left: 4px solid #0f766e; color: #23404d !important; line-height: 1.75 !important;',
      code: 'font-family: "SF Mono", Menlo, Consolas, monospace; font-size: 14px; padding: 2px 6px; background-color: #eefbf8 !important; color: #0f766e !important; border-radius: 4px;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #102a43 !important; color: #f8fbff !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 40px 0; border: none; height: 1px; background-color: #cfe8e5 !important;',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 24px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'font-size: 14px; line-height: 1.6 !important; background-color: #ecfdf9 !important; padding: 10px 12px; text-align: left; border: 1px solid #cfe8e5; font-weight: 600; color: #14323f !important;',
      td: 'font-size: 15px; line-height: 1.6 !important; padding: 10px 12px; text-align: left; border: 1px solid #cfe8e5; color: #17202a !important;',
      tr: 'border-bottom: 1px solid #cfe8e5;',
    }
  },

  'warm-notes': {
    name: '轻品牌手记',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0px 40px 0px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Helvetica Neue", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #2a211c !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #2a211c !important; line-height: 1.3 !important; margin: 40px 0 20px; background: linear-gradient(90deg, #f59e0b, #ea580c); -webkit-background-clip: text; -webkit-text-fill-color: transparent !important;',
      h2: 'font-size: 24px; font-weight: 700; color: #2a211c !important; line-height: 1.35 !important; margin: 32px 0 16px; padding-left: 12px; border-left: 4px solid #f59e0b;',
      h3: 'font-size: 20px; font-weight: 600; color: #4a342b !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #6a4737 !important; line-height: 1.45 !important; margin: 24px 0 12px;',
      h5: 'font-size: 16px; font-weight: 600; color: #7a5746 !important; line-height: 1.5 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 600; color: #8b6958 !important; line-height: 1.5 !important; margin: 16px 0 8px;',
      p: 'font-size: 15px; margin: 20px 0 !important; line-height: 1.75 !important; color: #2a211c !important;',
      strong: 'font-weight: 700; color: #2a211c !important; background-color: rgba(245, 158, 11, 0.14) !important; padding: 1px 4px; border-radius: 4px;',
      em: 'font-style: italic; color: #7a5746 !important;',
      a: 'color: #ea580c !important; text-decoration: none; border-bottom: 1px solid #fdba74;',
      ul: 'margin: 20px 0; padding-left: 24px;',
      ol: 'margin: 20px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.75 !important; color: #2a211c !important;',
      blockquote: 'font-size: 15px; margin: 24px 0; padding: 16px 20px; background-color: #fff7ed !important; border-left: 4px solid #f59e0b; color: #5a4337 !important; line-height: 1.75 !important; border-radius: 6px;',
      code: 'font-family: "SF Mono", Menlo, Consolas, monospace; font-size: 14px; padding: 2px 6px; background-color: #fff1db !important; color: #c2410c !important; border-radius: 4px;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #2f241f !important; color: #fff8f1 !important; border-radius: 10px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 40px 0; border: none; height: 1px; background-color: #fed7aa !important;',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 24px auto; border-radius: 10px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'font-size: 14px; line-height: 1.6 !important; background-color: #fff7ed !important; padding: 10px 12px; text-align: left; border: 1px solid #fed7aa; font-weight: 600; color: #4a342b !important;',
      td: 'font-size: 15px; line-height: 1.6 !important; padding: 10px 12px; text-align: left; border: 1px solid #fed7aa; color: #2a211c !important;',
      tr: 'border-bottom: 1px solid #fed7aa;',
    }
  },
};
